routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index');

Auth::routes();

Route::middleware('auth')->group(function () {
	Route::get('/home', 'DashboardController@index')->name('dashboard');
	Route::resource('/category', 'CategoryController');
	Route::resource('/product', 'ProductController');
});

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Carbon\Carbon;
class Category extends Model
{
    use SoftDeletes;
    
    protected $table = 'categories';
    public $timestamps = true;
    public $primaryKey = 'category_id';

    public function scopeSortByName($query)
    {
    	return $query->orderBy('category_name', 'ASC');
    }

    public function scopeSearch($query, $search)
    {
    	if($search)
    	{
    		return $query->whereRaw("MATCH(category_name,category_description) AGAINST(?)", array($search));
    	}
    }

}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Validation\Rule;

use App\Models\Category;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $data['Categories'] = Category::search($request->search)->paginate(10);

        return view('admin.category.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validated = $request->validate([
            'category_name' => ['required', Rule::unique('categories')->whereNull('deleted_at')]
        ]);

        $Category = new Category;
        $Category->category_name = $request->category_name;
        $Category->category_description = $request->category_description;
        $Category->save();

        return response()->json(['message' => 'Category '.$Category->category_name.' created', 'status' => 1]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['Category'] = Category::findOrFail($id);

        return view('admin.category.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $Category = Category::findOrFail($id);

        $validated = $request->validate([
            'category_name' => ['required', Rule::unique('categories')->ignore($Category->category_id, 'category_id')->whereNull('deleted_at')]
        ]);

        $Category->category_name = $request->category_name;
        $Category->category_description = $request->category_description;
        $Category->save();

        return response()->json(['message' => 'Category '.$Category->category_name.' updated', 'status' => 1]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $Category = Category::findOrFail($id);
        $Category->delete();

        return response()->json(['message' => 'Category '.$Category->category_name.' deleted', 'status' => 1]);
    }
}

resources/views/admin/category/create.blade.php
<form method="POST" class="form-category-create" action="{{route('category.store')}}">
    {!! csrf_field() !!}
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Category Create</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div>
            <label>Name</label>
            <input type="text" class="form-control category_name_input_create" name="category_name" required="required" value="{{ request()->input('category_name', old('category_name')) }}">
        </div>
        <div>
            <label>Description</label>
            <textarea class="form-control category_description_input_create" name="category_description">{{ request()->input('category_description', old('category_description')) }}</textarea>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary btn-create-category"  >Save</button>
      </div>
    </div>
</form>

resources/views/admin/category/edit.blade.php
<form method="POST" class="form-category-create" action="{{route('category.update', $Category->category_id)}}">
    {!! csrf_field() !!}
    {{ method_field('PUT') }}
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Edit Category</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div>
            <label>Name</label>
            <input type="text" class="form-control" name="category_name" required="required" value="{{ request()->input('category_name', old('category_name', $Category->category_name)) }}">
        </div>
        <div>
            <label>Description</label>
            <textarea class="form-control" name="category_description" >{{ request()->input('category_description', old('category_description', $Category->category_description)) }}</textarea>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary btn-create-category"  >Save</button>
      </div>
    </div>
</form>

resources/views/admin/category/index.blade.php
@extends('layouts.app')

@section('content')
<div class="reload-data">
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">

            @if(session()->has('message'))
                 <div class="alert alert-success alert-dismissible"><a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>{{session('message')}}</div>
            @endif

            <div class="card ">
                <div class="card-header">Category List <button class="btn btn-primary btn-sm float-right btn-category-popup" data-toggle="modal" data-target="#createCategoryModal" href="{{route('category.create')}}">Create</button></div>

                <div class="card-body table-responsive">
                    <div>
                        <form method="GET" class='search-no-refresh-category' action="{{route('category.index')}}">
                            <div class="input-group">
                                <input type="text" class="form-control" placeholder="Search" name="search" value="{{ request()->input('search', old('search')) }}">
                                <div class="input-group-append">
                                  <button class="btn btn-secondary" type="submit">
                                    Search
                                  </button>
                                </div>
                            </div>
                        </form>
                    </div>
                    <br />
                    <table class="table table-bordered ">
                        <tr>
                            <th>Name</th>
                            <th>Description</th>
                            <th></th>
                        </tr>

                        <tbody class="reload-body">
                            @if(count($Categories) >= 1)
                                @foreach($Categories as $key => $category)
                                    <tr>
                                        <td>{{$category->category_name}}</td>
                                        <td>{{$category->category_description}}</td>
                                        <td>
                                            <center>
                                                <button type="button" class='btn btn-primary btn-sm btn-category-popup' data-toggle="modal" data-target="#createCategoryModal" href="{{route('category.edit', $category->category_id)}}">Edit</button>
                                                <a class="btn btn-danger btn-sm btn-delete-category" action="{{route('category.destroy', $category->category_id)}}" name="{{$category->category_name}}" id="{{$category->category_id}}" >Delete</a>
                                            </center>
                                        </td>
                                    </tr>
                                @endforeach
                            @else
                                <tr><td colspan="20"><center>--No Data Found--</center></td></tr>
                            @endif
                        </tbody>
                    </table>
                </div>
                <div class="card-footer"><center>{{ $Categories->appends(request()->query())->links() }}</center></div>
            </div>
        </div>
    </div>
</div>



    <!-- Modal -->
    <div class="modal fade" id="createCategoryModal" tabindex="-1" role="dialog" aria-labelledby="createCategoryModal" aria-hidden="true">
      <div class="modal-dialog modal-dialog-category" role="document">
        <form method="POST" class="form-category-create" action="{{route('category.store')}}">
            {!! csrf_field() !!}
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Category Create</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <div>
                    <label>Name</label>
                    <input type="text" class="form-control category_name_input_create" name="category_name" required="required" value="{{ request()->input('category_name', old('category_name')) }}">
                </div>
                <div>
                    <label>Description</label>
                    <textarea class="form-control category_description_input_create" name="category_description">{{ request()->input('category_description', old('category_description')) }}</textarea>
                </div>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary btn-create-category"  >Save</button>
              </div>
            </div>
        </form>   
      </div>
    </div>

    <form class="category-form-delete" method="post" action="">
        {!! csrf_field() !!} {{ method_field('DELETE') }}
    </form>

</div>

@endsection

@section('scripts')
<link rel="stylesheet" href="{{ asset('js/jquery/jquery.confirm/jquery-confirm.min.css')}}">
<link rel="stylesheet" href="{{ asset('js/jquery/toast/jquery.toast.min.css')}}">
<script src="{{ asset('js/jquery/jquery.confirm/jquery-confirm.min.js')}}"></script>

<script src="{{ asset('js/jquery/popper.js/js/popper.min.js')}}"></script>
<script src="{{ asset('js/jquery/bootstrap/js/bootstrap.min.js')}}"></script>

<script src="{{ asset('js/jquery/toast/jquery.toast.min.js')}}"></script>
<script src="/js/admin/category.js?v=1.09"></script>
@endsection