routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index');

Auth::routes();

Route::middleware('auth')->group(function () {
	Route::get('/home', 'DashboardController@index')->name('dashboard');
	Route::resource('/category', 'CategoryController');
	Route::resource('/product', 'ProductController');
});

resources/views/admin/dashboard.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    <div>Total Products: <a href="{{route('product.index')}}">{{$ProductCount}}</a></div>
                    <div>Total Categories: <a href="{{route('category.index')}}">{{$CategoryCount}}</a></div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection