routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index');

Auth::routes();

Route::middleware('auth')->group(function () {
	Route::get('/home', 'DashboardController@index')->name('dashboard');
	Route::resource('/category', 'CategoryController');
	Route::resource('/product', 'ProductController');
});

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Carbon\Carbon;

use App\Models\Category;
class Product extends Model
{
    use SoftDeletes;
    
    protected $table = 'products';
    public $timestamps = true;
    public $primaryKey = 'product_id';


    public function category()
    {
        return $this->belongsTo(Category::class, 'category_id', 'category_id')->withTrashed();
    }

    public function scopeSearch($query, $search)
    {
    	if($search)
    	{
    		return $query->whereRaw("MATCH(product_name,product_description) AGAINST(?)", array($search));
    	}
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Models\Product;
use App\Models\Category;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $data['Products'] = Product::with('category')->search($request->search)->paginate(10);

        return view('admin.product.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['Categories'] = Category::SortByName()->get();

        return view('admin.product.create', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validated = $request->validate([
            'product_name' => 'required|max:100',
            'category' => 'required|exists:categories,category_id',
            'product_price' => 'required|min:0'
        ]);

        $Product = new Product;
        $Product->product_name = $request->product_name;
        $Product->product_description = $request->product_description;
        $Product->product_price = $request->product_price;
        $Product->category_id = $request->category;
        $Product->save();

        return redirect()->route('product.index')->with(['message' => 'Product '.$Product->product_name.' created']);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['Product'] = Product::findOrFail($id);
        $data['Categories'] = Category::SortByName()->get();

        return view('admin.product.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validated = $request->validate([
            'product_name' => 'required|max:100',
            'category' => 'required|exists:categories,category_id',
            'product_price' => 'required|min:0'
        ]);

        $Product = Product::findOrFail($id);
        $Product->product_name = $request->product_name;
        $Product->product_description = $request->product_description;
        $Product->product_price = $request->product_price;
        $Product->category_id = $request->category;
        $Product->save();

        return redirect()->route('product.index')->with(['message' => 'Product '.$Product->product_name.' updated']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $Product = Product::findOrFail($id);
        $Product->delete();

        return redirect()->route('product.index')->with(['message' => 'Product '.$Product->product_name.' deleted']);
    }
}

resources/views/admin/product/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-4 mx-auto">
            <form method="POST" action="{{route('product.store')}}">
                {!! csrf_field() !!}
                <div class="card">
                    <div class="card-header">Create Product</div>

                    <div class="card-body">
                        <div>
                            <label>Name</label>
                            <input type="text" class="form-control" name="product_name" required="required" value="{{ request()->input('product_name', old('product_name')) }}">
                        </div>
                        <div>
                            <label>Description</label>
                            <textarea class="form-control" name="product_description" required="required">{{ request()->input('product_description', old('product_description')) }}</textarea>
                        </div>
                        <div>
                            <label>Price</label>
                            <input type="number" min="0" step="any" class="form-control" name="product_price" required="required" value="{{ request()->input('product_price', old('product_price')) }}">
                        </div>
                        <div>
                            <label>Category</label>
                            <select class="form-control" name="category">
                                @foreach($Categories as $key => $value)
                                    <option value="{{$value->category_id}}" {{ request()->input('product_price', old('product_price')) == $value->category_id ? 'selected' : '' }} >{{$value->category_name}}</option>
                                @endforeach
                            </select>
                        </div>

                    </div>
                    <div class="card-footer">
                        @if($errors->any())
                            <div class="alert alert-danger col-md-12">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif
                        <button class='btn btn-primary float-right' type="submit">Save</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/admin/product/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-4 mx-auto">
            <form method="POST" action="{{route('product.update', $Product->product_id)}}">
                {!! csrf_field() !!}
                {{ method_field('PUT') }}
                <div class="card">
                    <div class="card-header">Update Product</div>

                    <div class="card-body">
                        <div>
                            <label>Name</label>
                            <input type="text" class="form-control" name="product_name" required="required" value="{{ request()->input('product_name', old('product_name', $Product->product_name)) }}">
                        </div>
                        <div>
                            <label>Description</label>
                            <textarea class="form-control" name="product_description" required="required">{{ request()->input('product_description', old('product_description', $Product->product_description)) }}</textarea>
                        </div>
                        <div>
                            <label>Price</label>
                            <input type="number" min="0" step="any" class="form-control" name="product_price" required="required" value="{{ request()->input('product_price', old('product_price', $Product->product_price)) }}">
                        </div>
                        <div>
                            <label>Category</label>
                            <select class="form-control" name="category">
                                @foreach($Categories as $key => $value)
                                    <option value="{{$value->category_id}}" {{ request()->input('product_price', old('product_price', $Product->category_id)) == $value->category_id ? 'selected' : '' }}>{{$value->category_name}}</option>
                                @endforeach
                            </select>
                        </div>

                    </div>
                    <div class="card-footer">
                        @if($errors->any())
                            <div class="alert alert-danger col-md-12">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif
                        <button class='btn btn-primary float-right' type="submit">Save</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/admin/product/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">

            @if(session()->has('message'))
                 <div class="alert alert-success alert-dismissible"><a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>{{session('message')}}</div>
            @endif

            <div class="card">
                <div class="card-header">Product List <a class="btn btn-primary btn-sm float-right" href="{{route('product.create')}}">Create</a></div>

                <div class="card-body table-responsive">
                    <div>
                        <form method="GET" action="{{route('product.index')}}">
                            <div class="input-group">
                                <input type="text" class="form-control" placeholder="Search" name="search" value="{{ request()->input('search', old('search')) }}">
                                <div class="input-group-append">
                                  <button class="btn btn-secondary" type="submit">
                                    Search
                                  </button>
                                </div>
                            </div>
                        </form>
                    </div>
                    <br />
                    <table class="table table-bordered ">
                        <tr>
                            <th>Name</th>
                            <th>Price</th>
                            <th>Description</th>
                            <th>Category</th>
                            <th></th>
                        </tr>

                        <tbody>
                            @if(count($Products) >= 1)
                                @foreach($Products as $key => $Product)
                                    <tr>
                                        <td>{{$Product->product_name}}</td>
                                        <td>{{number_format($Product->product_price, 2)}}</td>
                                        <td>{{$Product->product_description}}</td>
                                        <td>{{$Product->category->category_name}}</td>
                                        <td>
                                            <center>
                                                <form class="product-form-{{$Product->product_id}}" method="post" action="{{route('product.destroy', $Product->product_id)}}">
                                                    {!! csrf_field() !!} {{ method_field('DELETE') }}
                                                </form>
                                                <a class='btn btn-primary btn-sm' href="{{route('product.edit', $Product->product_id)}}">Edit</a>
                                                <button class="btn btn-danger btn-sm btn-delete-product" name="{{$Product->product_name}}" id="{{$Product->product_id}}" >Delete</button>
                                            </center>
                                        </td>
                                    </tr>
                                @endforeach
                            @else
                                <tr><td colspan="20"><center>--No Data Found--</center></td></tr>
                            @endif
                        </tbody>
                    </table>
                </div>
                <div class="card-footer"><center>{{ $Products->appends(request()->query())->links() }}</center></div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('scripts')
<link rel="stylesheet" href="{{ asset('js/jquery/jquery.confirm/jquery-confirm.min.css')}}">
<script src="{{ asset('js/jquery/jquery.confirm/jquery-confirm.min.js')}}"></script>
<script src="/js/admin/product.js?v=1.09"></script>
@endsection